### ISSUE TITLE
Missing Module Error

### ISSUE THREAD

**Issue by gjackson12** [ckan/ckanext-dcat#102]
When I attempt to start CKAN after installing dcat, I see an error that says, "ImportError, No module named harvest.model". I assume I'm missing a module obviously but the instructions don't mentioned anything about installing an additional package.

**Comment by gjackson12** [comment]
User error. 😄

**Comment by ho9science** [comment]
@gjackson12 would you tell me what kinds of user error?

**Comment by ho9science** [comment]
notice for same problem, install ckanext-harvest.

[ckanext-harvest](https://github.com/ckan/ckanext-harvest)
