### ISSUE TITLE
mapping DCAT-AP and CKAN is recent?

### ISSUE THREAD

**Issue by GeraldGrootRoessink** [ckan/ckanext-dcat#109]
Some time ago the EU published a mapping between DCAT en CKAN. See: https://gitlab.com/european-data-portal/ckanext-edp/wikis/schema. This mapping corresponds to the mapping in de readme-file but with differences.  I would appreciate some thoughts about the best way forward.
Thanks, Gerald

**Comment by amercader** [comment]
@GeraldGrootRoessink the EU portal extension and this one are two different implementations of a DCAT-AP / CKAN mapping. They were developed separately and as you noticed there are some differences. You should use the one that best matches your needs.
As for ckanext-dcat, the mapping was last updated to support DCAT-AP 1.1.

**Comment by GeraldGrootRoessink** [comment]
Recent activity would be a criterion :-)  Many thanks. I'm still wondering about a thing. The mapping that is published here, seems rather complete, but de converters.py covers about one fourth of it.  Is that the extent of it?

**Comment by amercader** [comment]
@GeraldGrootRoessink `converters.py` is an old legacy file from a previous implementation. The current implementation is handled in [`profiles.py`](https://github.com/ckan/ckanext-dcat/blob/master/ckanext/dcat/profiles.py).

**Comment by GeraldGrootRoessink** [comment]
that's  good news.
