### ISSUE TITLE
Small issue with 2.8.1

### ISSUE THREAD

**Issue by AzzurraP** [ckan/ckanext-dcat#128]
Hello, I submit just a small issue:
With current last stable version ""2.8.1", the metadata is not rendered

Log file:
[Tue Aug 07 17:20:02.817043 2018] [wsgi:error] [pid 9861:tid 140173446534912] [remote 127.0.0.1:64165] File '/usr/lib/ckan/default/src/ckanext-dcat/ckanext/dcat/controllers.py', line 18 in <module>
[Tue Aug 07 17:20:02.817066 2018] [wsgi:error] [pid 9861:tid 140173446534912] [remote 127.0.0.1:64165]   from ckan.views.dataset import read as read_endpoint
[Tue Aug 07 17:20:02.817087 2018] [wsgi:error] [pid 9861:tid 140173446534912] [remote 127.0.0.1:64165] ImportError: No module named dataset

Fixed this way (Error at line 18 of /ckanext/dcat/controllers.py) in  my env: 
"if toolkit.check_ckan_version(max_version='2.8.1'):"

**Comment by amercader** [comment]
Thanks @AzzurraP, I'll have a look as soon as I can

**Comment by amercader** [comment]
@AzzurraP this should be fixed on latest master (986517)
