### ISSUE TITLE
Use OWL-Time for temporal extent

### ISSUE THREAD

**Issue by dr-shorthair** [ckan/ckanext-dcat#136]
The [Time Ontology in OWL](https://www.w3.org/TR/owl-time/) was (finally) upgraded from a _submission_ to a _W3C Recommendation_ in 2017. This provides proper structures for temporal information, with a variety of representations of temporal position to support specialized scenarios. The simplest pattern for a temporal extent looks like: 
``` turtle
   dct:temporal [
      time:hasBeginning [
         time:inXSDDate "2016-01-01"^^xsd:date
      ] ;
      time:hasEnd [
         time:inXSDDate "2017-12-31"^^xsd:date
      ] ;
   ] ;
```

**Comment by seitenbau-govdata** [comment]
This was fixed with commit https://github.com/ckan/ckanext-dcat/commit/7475fdc7e380d1e70080575e69a6c0c8ebc85ea4.
