### ISSUE TITLE
RDF examples and update of docs...

### ISSUE THREAD

**Issue by kentsanggds** [ckan/ckanext-dcat#153]
The DCAT README doc contains some links to a demo site which doesn't seem to work, they keep on 404ing.

Would it be possible to get the demo site working with the described links so that a working RDF structure can be viewed or provide a template on the README for the actual rdf template to be available.

**Comment by archaeogeek** [comment]
A big +1 for this! The links that 404 are the ones here: https://github.com/ckan/ckanext-dcat#rdf-dcat-endpoints. While there is a working link to a catalog endpoint further down the readme, the endpoint for a single dataset is most useful for templating and debugging.

**Comment by simeonackermann** [comment]
The link to http://publicdata.eu in the readme is obsolete too - currently its a kind of porn aggregation site ... ;)

**Comment by amercader** [comment]
@simeonackermann thanks for flagging this. I have now removed that link. @kentsanggds @archaeogeek I've replaced the demo.ckan.org dataset links with some live ones from the Swiss national park which hopefully are more stable (cc @metaodi )
