### ISSUE TITLE
CKAN 2.7.2 Error - <class 'ckan.logic.NotAuthorized'>:

### ISSUE THREAD

**Issue by gallexme** [ckan/ckanext-dcat#155]
When i open the Catalog.rdf i get:
Error - <class 'ckan.logic.NotAuthorized'>:
what could be the issue/which infos do u need?

dataset/nameofdataset.rdf works tho

**Comment by metaodi** [comment]
Can you provide a stacktrace (from the CKAN and/or apache logfile)? This would help to narrow down the error.

**Comment by gallexme** [comment]
@metaodi 
https://gist.github.com/gallexme/01169898f59e82c6053dd297e1fd18e7

**Comment by gallexme** [comment]
@metaodi  any updates?
