### ISSUE TITLE
Distribution's format type in DCAT XML

### ISSUE THREAD

**Issue by montxo5** [ckan/ckanext-dcat#17]
Hello again... Now that its all working great, we see that there are a lot of Distribution formats like this: application/rdf+xml or application/rss+xml, application/gzip.

Then, when it harvest the datasets, the resource's formats are equals in ckan. So, when we try to previsualize or search the resources, the format does not look "good".

Could it be possible to make some kind of mapping for this formats? Or maybe ignore de "application/" and the "+xml" when inserts?

Thanks.

**Comment by amercader** [comment]
The RDF harvester (`dcat_rdf_harvester`) handles this, setting up resource['format'] and resource['mimetype'] properly from the DCAT fields. Please use this harvester instead of the XML based one (https://github.com/ckan/ckanext-dcat#xml-dcat-harvester-deprecated)
