### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by gallexme** [ckan/ckanext-dcat#182]
Hey,

what am im doing wrong if i set the Licence as usual in the Dataset, and the Distributions dont get a License Field???/the DCAT Catalogue doesnt have any license :(

shouldnt the license of the Dataset be copied to all Distributions(Aka  Ressources in CKAN?)

**Comment by amercader** [comment]
Looks like the [`graph_from_dataset()`](https://github.com/ckan/ckanext-dcat/blob/master/ckanext/dcat/profiles.py#L1055) method of the base profile doesn't try to import the dataset license to the distributions (the inverse, distribution license -> dataset license, was implemented a while ago)
This would be need to be implemented.

**Comment by gallexme** [comment]
Would it be possible to have it implemented, since Licenses are Very important dont you think ? :) , and reading it from the Dataset which already has the License seems like the first logical step, 
sorry i am just slightly flabbergasted that licenses are not working in a 5 year old project.


Feature idea:
1. Read License from Dataset
2. Output it in the DCAT Formats

**Comment by seitenbau-govdata** [comment]
Now there is a configuration option https://github.com/ckan/ckanext-dcat#inherit-license-from-the-dataset-as-fallback-in-distributions to enable the inheritance of the license from the dataset to the distributions.
