### ISSUE TITLE
beautifulsoup4 v4.3.2 not supported by Python v3.5+

### ISSUE THREAD

**Issue by alycejenni** [ckan/ckanext-dcat#192]
Is there a specific reason that beautifulsoup4 is set to v4.3.2 in dev_requirements.txt, or has there just not been a reason to update it?
https://github.com/ckan/ckanext-dcat/blob/6b7ec505f303fb18e0eebcebf67130d36b3dca82/dev-requirements.txt#L1

Using the default or `html5lib` parser with bs4 in Python 3.5+ results in import errors for `HtmlParseError`, since it was [removed in 3.5](https://bugs.python.org/issue15114). Updating to bs4 v4.4.0+ fixes it.

(I'm not actually getting errors from ckanext-dcat by itself, just when it's used with other plugins that also use bs4!)

**Comment by amercader** [comment]
@alycejenni there's no reason to not update it. TBH I think we should be fine leaving the dev requirements unpinned. 
And actually I don't think ckanext-dcat actually uses BS for anything does it? If so it can just be removed
