### ISSUE TITLE
Old version of rdflib

### ISSUE THREAD

**Issue by frafra** [ckan/ckanext-dcat#207]
`requirements.txt` has not been updated for a while. `rdflib` is pinned to 4.2.1, which has been released ~7 years ago.
It could be a good time to upgrade it.

https://github.com/ckan/ckanext-dcat/blob/56eb2459293754a57a47bb2b7c0273d2d7263ae0/requirements.txt#L1

**Comment by amercader** [comment]
@frafra yes, it would be great to update all requirements on requirements.txt

Feel free to send a PR

**Comment by seitenbau-govdata** [comment]
Related PR: https://github.com/ckan/ckanext-dcat/pull/213

**Comment by seitenbau-govdata** [comment]
@frafra Fixed with https://github.com/ckan/ckanext-dcat/pull/213 If not, please reopen the issue.
