### ISSUE TITLE
ckanext-harvest mandatory or not

### ISSUE THREAD

**Issue by rmeissn** [ckan/ckanext-dcat#212]
Within the readme, the first installation instruction is:
`Install ckanext-harvest (https://github.com/ckan/ckanext-harvest#installation) (Only if you want to use the RDF harvester)`
This sounded to me like ckanext-harvest is optional - "Only if ...." - but according to https://github.com/ckan/ckanext-dcat/issues/204#issuecomment-1000185669 this extension is mandatory.
Is ckanext-harvest an optional or mandatory extension to install ckanext-dcat? The answer should be added to the Readme.

**Comment by seitenbau-govdata** [comment]
The extension `ckanext-harvest` is optional. Our comment was in a different context, because the other person have had defined the harvester plugins within the line `ckan.plugins` in the CKAN configuration file, and then `ckanext-harvest` is required.

**Comment by rmeissn** [comment]
Many thanks for the clarification!
