### ISSUE TITLE
Error parsing distribution formats

### ISSUE THREAD

**Issue by dportoles** [ckan/ckanext-dcat#22]
When I parse a DCAT with distribution formats, parser doesn't read format properly and assign a different (and strange) value to format.

For the example above, instead of application/rdf

First time I get:  "format": "N13e858a1e0e048d8b093e52f2b310c6a"
Next time I get: "format": "N37e70a18f243496fa0a9b95e49a188e6"
(...)

My DCAT file is  https://www.dropbox.com/s/p6n2xf4gm6p8hao/dcat-mini.rdf

Thanks in advance

**Comment by amercader** [comment]
@dportoles should be fixed now, can you pull latest master and give it a try?
