### ISSUE TITLE
Making a new profile for Dcat v.2.0

### ISSUE THREAD

**Issue by sparsons808** [ckan/ckanext-dcat#221]
My organization is looking to make use of some of the optional fields that are now available with Dcat v.2.0.

For example:
Add dct:creator (Optional property)
Add dct:isReferencedBy (Optional property)
Add prov:qualifiedAttribution (Optional property)
Add dcat:spatialResolutionInMeters (Optional property)
Add dcat:temporalResolution (Optional property)
Add adms:versionNotes (Optional property)
Add prov:wasGeneratedBy (Optional property)

Could you all give some insight on how to create a new profile to make us of these fields? Or give me an idea on how to add to an existing profile. For example could I just add dct:creator to the parse_dataset function within the EuropeanDCATAPProfile class? Thank you for any help you all may offer.

**Comment by metaodi** [comment]
You should extend the `ckanext.dcat.profiles.RDFProfile` class, then your code should be compatible.

I would highly recommend to create a new profile to have more freedom unless it's really only to add a couple of fields.

As for the harvester: you can use the profile to parse datasets from a remote site (using the RDF harvester of this extension). But it's recommended to add the new fields to your CKAN instance using something like ckanext-scheming. Hope this helps.

**Comment by sparsons808** [comment]
thank you, this helps.

**Comment by metaodi** [comment]
Btw: make sure to check issue #168 and PR #220

**Comment by sparsons808** [comment]
I wrote a custom profile and when i run the parse command I get an unknow rdf profiles error. does anyone know why this may bet. I have my custom profile in setup.py and in my ckan ini file as well as in the the default rdf profiles list. I have also tried to put it directly in the profiles list given to the init method. Any help is helpful, thank you.

**Comment by sparsons808** [comment]
also I put some breakpoints in profiles.py and when I run the parse command it seems to not be hitting profiles.py at all yet still parsing my jsonld file.

**Comment by amercader** [comment]
@sparsons808 can you open a new issue, making sure to include the full error you are getting? cheers

Closing this in favour of #168
