### ISSUE TITLE
does the harvester/dcat have the ability to parse an entire catalog with multiple datasets and their distributions at once.

### ISSUE THREAD

**Issue by sparsons808** [ckan/ckanext-dcat#227]
Looking for clarification on this. please advise, need to know if this is possible or if I need to build my own way to do it. a catalog.jsonld file that holds multiple datasets and distributions for those datasets can ckan ingest these files parse them with dcat and load them all at once.

**Comment by sparsons808** [comment]
so basically this is only compatible with other sites using ckan?

**Comment by sparsons808** [comment]
so if I was trying to get a catalog from from another source I would say something like data.gov/catalog.jsonld?profile=euro_dcat_ap and this would grab data.govs catalog and load into my instance?

**Comment by sparsons808** [comment]
@metaodi

**Comment by metaodi** [comment]
It's compatible with any source that provides valid DCAT RDF. I'm familiar with the setup in Switzerland where opendata.swiss has several harvesters setup from different sources. All of those sources provide valid DCAT, but only some of them are using CKAN. Others use OpenDataSoft or custom software to generate DCAT RDF.

You can actually check the config of the harvesters, e.g. here is one harvesting from another CKAN instance: https://ckan.opendata.swiss/api/3/action/harvest_source_show?id=9a2e4ae1-62b2-431d-913e-aeaa42988ec5 (or check the full list with https://ckan.opendata.swiss/api/3/action/harvest_source_list)

As you can see the source is set to https://data.stadt-zuerich.ch/catalog.xml?fq=-tags:ktzh (so this transfers all datasets except those with the tag `ktzh`)

**Comment by sparsons808** [comment]
@metaodi what are you thoughts on catalog that have parent datasets with children datasets. I have had hard time parsing catalogs with datasets that have child datasets.

**Comment by metaodi** [comment]
Data product is afaik not defined by DCAT, but DCAT 2 has ["qualified realation"](https://www.w3.org/TR/vocab-dcat-2/#Property:resource_qualified_relation), so you could use those to link datasets together (e.g. using `dct:partOf`).

Depending on the use case the new DCAT 3 class `DatasetSeries` could be a solution, too.

**Comment by sparsons808** [comment]
@metaodi thank you for this!
