### ISSUE TITLE
schemaorg profile not working

### ISSUE THREAD

**Issue by sparsons808** [ckan/ckanext-dcat#228]
each time i try to use the schemaorg profile I receive an empty dictionary. schemaorg is specified in my setup.py file. Is there any other reason this could be happening?

**Comment by metaodi** [comment]
How do you try to use the `schemaorg` profile? Using the catalog endpoint? Or the dataset endpoint? With what call?

Do you have data that can be mapped to `schemaorg`?

Please give more information about what you try to do and error messages etc. you get.
