### ISSUE TITLE
Should adms:version & adms:contactpoint be owl:versionInfo & dcat:contactpoint?

### ISSUE THREAD

**Issue by deirdrelee** [ckan/ckanext-dcat#24]
Hi, 
Should adms:version be owl:versioninfo (as per http://www.w3.org/TR/vocab-adms/#owl-versioninfo) and adms:contactpoint be dcat:contactpoint (as per http://www.w3.org/TR/vocab-dcat/)?
Cheers

**Comment by akuckartz** [comment]
Why?

**Comment by akuckartz** [comment]
Ah, I see: some documents published by the EC are not up to date. Good catch !

**Comment by amercader** [comment]
@deirdrelee Sorry for the late reply. You are right, I was following the guidance from the current EC DCAT-AP spec. The revised version includes the corrections you mention:

https://joinup.ec.europa.eu/node/137964/

I'll update the parses/serializers accordingly

**Comment by amercader** [comment]
Fixed in 0d913946ddd70fa355be11e92e10a89c2aabe2c7 and 29686a703cea3c497659a69a1dbd607725dda4e1
