### ISSUE TITLE
New version for dropped Py2 and CKAN<2.9 support

### ISSUE THREAD

**Issue by bellisk** [ckan/ckanext-dcat#247]
Could someone who has the rights to do so please make a new release of this package to mark that old versions are no longer supported? (See https://github.com/ckan/ckanext-dcat/commit/5faebce9ab4030b5965dbac27ed426cda59fea41.)

Thanks!

**Comment by bellisk** [comment]
Okay, thank you :)

**Comment by seitenbau-govdata** [comment]
@bellisk The new version [v1.5.0](https://github.com/ckan/ckanext-dcat/releases/tag/v1.5.0) has been released.
