### ISSUE TITLE
"Fall-back" mapping for dcat generation

### ISSUE THREAD

**Issue by Hoedic** [ckan/ckanext-dcat#25]
The existing mapping rely at lot on extras. For example dct:issued maps to extra:issued while in the internal CKAN schema, there is a "creation date" attribute.

While I understand that for harvesting one might not want to override some important internal field with harvested data (e.g we want to keep track of the creation date in CKAN on top of the creation date of the original remote.

However, for DCAT generation, it might not be that relevant to use all these extra and it will be quite painful to create all those extras when they are not needed (e.g no dcat harvesting). So I would propose that for dcat generation, there is a fallback mechanism: whenever possible search for the extra (e.g extra:issued) and if not available fallback on the corresponding core attribute. 

In the same approach, there are several field that could follow this: dcat:theme (use the group), dct:identifier (use the internal identifier), dct:issued and  dct:modified (creation and last update), contact name and email (author and author email).  For the publisher info, there would probably be some fields at the organisation level.

**Comment by amercader** [comment]
@Hoedic that's totally sensible and it's what we were planning on doing.

BTW I'm working on DCAT generation the next couple of weeks, I'll let you know when it's ready for testing to get your feedback

**Comment by Hoedic** [comment]
:+1: If you have something in the next 2-3 weeks, we will definitely be in situation where we can test it.

**Comment by amercader** [comment]
Implemented as part of #28, fallbacks are described in https://github.com/ckan/ckanext-dcat#rdf-dcat-to-ckan-dataset-mapping
