### ISSUE TITLE
Support for DCAT 3

### ISSUE THREAD

**Issue by jze** [ckan/ckanext-dcat#257]
[DCAT 3](https://www.w3.org/TR/vocab-dcat-3/) (and the European draft [DCAT-AP 3](https://semiceu.github.io/DCAT-AP/releases/3.0.0/)) changes the structure of metadata significantly. Instead of *dataset* → *distribution* (or *package* → *resource* in CKAN terms) we now have *datasets*, *dataset series* and *data services* as first-class citizen entities. We are thus getting closer to the geo-world and ISO metadata. I wonder if we can even model this with the current structures in CKAN.

*Data services* have already been introduces in DCAT 2. However, it seems to me that they are not yet first-class citizen entities with an own entry in the `package` table. Instead they can just be found as JSON data in the `package_extra` table entry of a dataset.

The `package` table already contains a column `type` that might be used to distinguish between *dataset*, *dataset series* and *data service*. CKAN even uses the term `dataset` at this point today. The column is also used to indicate harvest sources (that are stored in the `package` table, too). I suspect, however, that major modifications to CKAN itself will be necessary to display these different entities.

**Comment by loleg** [comment]
Thanks for sharing. Would love to see an update from the team on a DCAT 3 roadmap for CKAN.

**Comment by amercader** [comment]
Closed in favour of https://github.com/ckan/ckanext-dcat/issues/271
