### ISSUE TITLE
process profiles in the order of declaration

### ISSUE THREAD

**Issue by pduchesne** [ckan/ckanext-dcat#31]
Currently profiles are taken in the order of their hosting extensions as sorted by the system (cf https://github.com/ckan/ckanext-dcat/blob/c8c7314c8f36b3c5c9ae136f36d48e1142744551/ckanext/dcat/parsers.py#L80#L80)
They should be ordered according to the config declaration ('ckanext.dcat.rdf.profiles').

**Comment by amercader** [comment]
Fixed in #32

**Comment by pduchesne** [comment]
For some merging reason, the above fix was applied on parsers.py, after the same file was renamed to processors.py in the revision history. As a result, the fix got lost and is missing in current master.

**Comment by amercader** [comment]
Fixed, thanks @pduchesne
