### ISSUE TITLE
Clarify what this is about

### ISSUE THREAD

**Issue by neothemachine** [ckan/ckanext-dcat#34]
I think it would be good if in the README there would be some sentence to explain the relation to the existing RDF functionality of CKAN: http://docs.ckan.org/en/latest/maintaining/linked-data-and-rdf.html

**Comment by amercader** [comment]
The existing functionality in CKAN will be removed and replace with this extension, I'll add a note to the README when this is done. BTW the README has been updated and is now hopefully easier to follow

**Comment by amercader** [comment]
The old LD page on the core docs now link to this extension, and the README has been updated.
Shout if you think this could be improved.

http://docs.ckan.org/en/latest/maintaining/linked-data-and-rdf.html
