### ISSUE TITLE
writing own profile

### ISSUE THREAD

**Issue by bvj** [ckan/ckanext-dcat#36]
Hi, i need to write my own rdf profile - especially graph_from_dataset part for rdf endpoint. To which file i have to save it? 

Thank you

**Comment by amercader** [comment]
You need to save it on a file in your own extension, and then reference it on the `setup.py` of your extension:

```
[ckan.rdf.profiles]
your_profila=ckanext.yourextension.your_profiles_file:YourProfile
```

Here are all the details:

https://github.com/ckan/ckanext-dcat#writing-custom-profiles
