### ISSUE TITLE
Harvester fails for JSON-LD

### ISSUE THREAD

**Issue by neothemachine** [ckan/ckanext-dcat#45]
I have a source of DCAT JSON-LD but always get:
```
Error parsing the RDF file: No plugin registered for (application/ld+json, <class 'rdflib.parser.Parser'>)
```
Why is this happening? I thought JSON-LD is one of the supported formats?

**Comment by neothemachine** [comment]
I also just checked if rdflib-jsonld is really installed in the ckan venv, and it is:

```
rdflib
rdflib-4.1.2-py2.7.egg-info
rdflib_jsonld
rdflib_jsonld-0.2-py2.7.egg-info
```

**Comment by neothemachine** [comment]
Found the bug. rdflib_jsonld expects "json-ld" as format string, however the harvester gives it "application/ld+json" and thus fails. I added `{"rdf_format":"json-ld"}` to the source config which works but obviously this is a work around. There should be mapping from content types to the format strings that rdflib actually understands. I wonder why no one else reported this problem?

**Comment by DieterDePaepe** [comment]
Support for anything other than XML is relatively new, it was added in the end of August by me. I guess nobody used json-ld yet. Your problem originates from an incorrect registration of the json-ld plugin in rdflib, it should be fixed on that side.

**Comment by akuckartz** [comment]
This is fixed in rdflib-jsonld (link in previous comment). Updating that library therfore should fix the current issue.
