### ISSUE TITLE
DCAT theme != literal string

### ISSUE THREAD

**Issue by letmaik** [ckan/ckanext-dcat#47]
The themes of a DCAT dataset are represented in this extension as a list of URLs only.. On export, you get something like:
```js
    "http://www.w3.org/ns/dcat#theme": [
      {
        "@value": "http://inspire.ec.europa.eu/theme/of"
      }
    ]
```

This is wrong. Theme is not a literal value but a skos:Concept which means that it has to be:
```js
    "http://www.w3.org/ns/dcat#theme": [
      {
        "@id": "http://inspire.ec.europa.eu/theme/of"
      }
    ]
```

**Comment by amercader** [comment]
Fixed by #66, please confirm if you have the change @letmaik
