### ISSUE TITLE
rdf harvester takes title as name, potentially non unique

### ISSUE THREAD

**Issue by pduchesne** [ckan/ckanext-dcat#54]
when harvesting a DCAT feed, the harvester takes the dcat:dataset title as CKAN name. (cf rdf.py#187)
But the name is unique in the CKAN model, while titles are potentially not, leading to harvest errors.

_gen_new_name function apparently takes care of that (appending random suffix to ensure uniqueness), but this does not work as it checks against already committed datasets, not those part of the same harvest job.

**Comment by seitenbau-govdata** [comment]
@amercader This should fixed by the commit https://github.com/ckan/ckanext-dcat/commit/be02f4a164cae6e88a0dc9078b43c4d20832e637 now, or not?

**Comment by quinoescobar** [comment]
@seitenbau-govdata This code solves my problem with long titles with almost the same string and only variaring in the end. 😄
