### ISSUE TITLE
RDF harvester doesn't seem to support paged catalogs?

### ISSUE THREAD

**Issue by JesseKlaasse** [ckan/ckanext-dcat#62]
While the ckanext-dcat extension does implement Hydra based paging in the exposed catalogs, the DCAT RDF harvester doesn't seem to support paged catalogs. Is this correct? And if so, is there a way to work around this issue?

**Comment by amercader** [comment]
@JesseKlaasse You are correct, the RDF harvester does not support the "semantic" Hydra-based pagination as it was implemented before the catalog endpoints.

I guess support for this could be added somewhere on the [`gather_stage`](https://github.com/ckan/ckanext-dcat/blob/master/ckanext/dcat/harvesters/rdf.py#L147).

**Comment by metaodi** [comment]
I made a PR to fix this. It basically checks if there is a HYDRA PagedCollection and simply runs the code in the gather_stage until there is no "nextPage" attribute present anymore.
