### ISSUE TITLE
Pagination uses toolkit.request.path_url instead of ckan.site_url

### ISSUE THREAD

**Issue by metaodi** [ckan/ckanext-dcat#68]
We're using the catalog output of ckanext-dcat for a CKAN instance and just realized, that the [pagination with HYDRA uses `toolkit.request.path_url`](https://github.com/ckan/ckanext-dcat/blob/54f6366a5c6368e70cc136b32fe7b2006f30ee27/ckanext/dcat/logic.py#L152) to determine the URL of the page. Because of our server/network setup, this now returns an internal URL, which is not accessible from the internet (the server is behind a proxy).

The obvious solution would be to use the CKAN option `ckan.site_url` instead to make sure, the URL is always the external one. Should the code be change to use this option? Or is there a specific use case where `toolkit.request.path_url` is the better option?

Alternatively we could introduce a new ckanext-dcat specific option to control wheter to use `site_url` or not. Something like `ckanext.dcat.always_use_site_url` with a boolean value.

**Comment by etj** [comment]
To be consistent, I guess the function ``catalog_uri()`` in utils.py should be used

https://github.com/ckan/ckanext-dcat/blob/v0.0.4/ckanext/dcat/utils.py#L60-L94

```
    The value will be the first found of:
        1. The `ckanext.dcat.base_uri` config option (recommended)
        2. The `ckan.site_url` config option
        3. `http://` + the `app_instance_uuid` config option (minus brackets)
```

**Comment by metaodi** [comment]
@etj please see my comment here: https://github.com/ckan/ckanext-dcat/pull/87#issuecomment-281343251

I think it's important to not mix up URL and URI here. While `ckan.site_url` is meant to return a valid URL, which can be used for paging, a URI must not necessarily be a URL that can be reached by HTTP. Just as you pointed out in your comment `http://` + the `app_instance_uuid` will most probably never lead to a valid URL that works for pagination.
