### ISSUE TITLE
after_show in DCATPlugin breaks custom theme

### ISSUE THREAD

**Issue by metaodi** [ckan/ckanext-dcat#82]
I just traced a bug to the [after_show method of the DCATPlugin](https://github.com/ckan/ckanext-dcat/blob/f9e090399b91fd92514ac8c783e3bd65d8cb3942/ckanext/dcat/plugins.py#L100-L113).

I was not expecting, that the `dcat` plugin would do anything with my theme, but it ended up overriding the names of some attributes on the resources in my theme.

E.g. my theme relies on the [existence of an attribute named `res.rights`](https://github.com/opendata-swiss/ckanext-switzerland/blob/f84e4045f34fd9b40d75e995e7cb2c55e6f409eb/ckanext/switzerland/templates/package/resource_read.html#L44), after activating the `dcat` plugin, this attribute is suddenly called `res.Rights`. (or [`res.download_url`](https://github.com/opendata-swiss/ckanext-switzerland/blob/f84e4045f34fd9b40d75e995e7cb2c55e6f409eb/ckanext/switzerland/templates/package/resource_read.html#L82) becomes `res.Download URL`)

I guess this is a convenience method to display the translated strings for all those that do not use a custom theme. But for those that do, this plugin might break it.

Is there a way to make this behavior optional or to put it in another plugin? What I now ended up doing is [overriding the DCATPlugin](https://github.com/opendata-swiss/ckanext-switzerland/blob/23a2b3456217a6e5e8c68d7ca850fb5cd5fc6ff4/ckanext/switzerland/dcat/plugins.py), but I'm not sure if this is something everybody has to do, that is in a similar situation like me.

**Comment by amercader** [comment]
This could definitely be wrapped in a config option switch (`ckanext.dcat.translate_keys`) that allowed to turn this behaviour off. Happy to take a PR for it @metaodi
