### ISSUE TITLE
broken markup on ext doc page

### ISSUE THREAD

**Issue by VladimirAlexiev** [ckan/ckanext-dcat#84]
Look at the bottom of section http://extensions.ckan.org/extension/dcat/#dataset-endpoints: the markup is broken.
There is no such breakage at https://github.com/ckan/ckanext-dcat/blob/master/README.md#rdf-dcat-to-ckan-dataset-mapping.
So I think the MD renderer that you use at the ext doc page is defective.

**Comment by VladimirAlexiev** [comment]
The breakage starts like this:
```
 ```xml
    ...and then goes on to
Another example:
  ``` @prefix dcat: http://www.w3.org/ns/dcat# . @prefix dct: http://purl.org/dc/terms/ . @prefix rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns# .
```

**Comment by amercader** [comment]
Thanks @VladimirAlexiev, this is an issue with the extensions.ckan.org parser. You should report the issue there: https://github.com/ckan/extensions.ckan.org
