### ISSUE TITLE
License element format

### ISSUE THREAD

**Issue by Faldrian** [ckan/ckanext-dcat#93]
Currently the `dcat:Distribution` has a node formatted like this:
`<dct:license>http://creativecommons.org/publicdomain/zero/1.0/</dct:license>`

https://joinup.ec.europa.eu/node/150347 states, that licenses should always be noted as URIs and their example puts the URI inside an `rdf:resource`-atttribute:
`<dct:license rdf:resource="http://creativecommons.org/publicdomain/zero/1.0/"/>`

Is there a good reason to not change the output to use the rdf:resource-notation if the value for dct:license is an URI? (non-URIs could be written in current format as Literal, in case somebody enters "All rights reserved" or something like that)

**Comment by akuckartz** [comment]
The statement on the Joinup page is a bit misleading. The domain of dct:license does not allow literals but only URIs. Therefore MUST, not should.

**Comment by seitenbau-govdata** [comment]
@Faldrian In my opinion this issue should be resolved by #140 now. Do you agree?

**Comment by Faldrian** [comment]
I think so, good work. :)
